
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VVD4
 */
public class ticketdata extends javax.swing.JInternalFrame {

    /**
     * Creates new form ticketdata
     */
    public ticketdata() {
        initComponents();
       ticketdata();
    }
        Connection con;
        PreparedStatement p;

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_tbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        txt_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ticketNo", "flightNo", "cusID", "class", "price", "seats", "Date"
            }
        ));
        jScrollPane1.setViewportView(txt_tbl);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void ticketdata()
    {
          try {
            Class.forName("com.mysql.jdbc.Driver");
             con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/airline" ,"root","");
             p = con.prepareStatement("select * from ticket");
             ResultSet rs = p.executeQuery();
             
             ResultSetMetaData rsm = rs.getMetaData();
            int c;
             c = rsm.getColumnCount();
             DefaultTableModel dfm = (DefaultTableModel)txt_tbl.getModel();
             dfm.setRowCount(0);
             
             while(rs.next())
                     {
                        Vector v2 = new Vector();
                        
                        for(int i = 1; 1 <= c; i++)
                            
                        {  
                        v2.add(rs.getString("id"));
                        v2.add(rs.getString("flightid"));
                        v2.add(rs.getString("cusid"));
                        v2.add(rs.getString("class"));
                        v2.add(rs.getString("price"));
                        v2.add(rs.getString("seats"));
                        v2.add(rs.getString("flightdate"));
                       
                        }
                         
                         dfm.addRow(v2);
                        }
             
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(booktic.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(booktic.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    
    }  
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable txt_tbl;
    // End of variables declaration//GEN-END:variables
}
